services:
  - type: web
    name: edith-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_MODE
        value: webhook
      - key: BOT_TOKEN
        sync: false
      - key: AI_API_KEY
        sync: false
      - key: APP_URL
        value: https://edith-bot.onrender.com
